###
GET http://localhost:8081/accounts

###
POST http://localhost:8081/accounts HTTP/1.1
Content-Type: application/json

{
  "userId": "5ff683e6-2c39-4eff-86f4-f4908da8ea86",
  "title": "test"
}

###
GET http://localhost:8081/accounts/160fab12-fc0a-46f2-854d-a7894cd76e78

###
PUT http://localhost:8081/accounts/160fab12-fc0a-46f2-854d-a7894cd76e78 HTTP/1.1
Content-Type: application/json

{
  "title": "new test!"
}

###
DELETE http://localhost:8081/accounts/160fab12-fc0a-46f2-854d-a7894cd76e78 HTTP/1.1
