###
GET http://localhost:8081/accounts

###
POST http://localhost:8081/accounts HTTP/1.1
Content-Type: application/json

{
  "ownerUserId": "5ff683e6-2c39-4eff-86f4-f4908da8ea86",
  "name": "test"
}

###
GET http://localhost:8081/accounts/bc17efe4-3fd0-443e-8ea4-b2eda8b383ae

###
PUT http://localhost:8081/accounts/af8ca419-9b44-4186-9f97-d4fa523b6d5c HTTP/1.1
Content-Type: application/json

{
  "name": "new test!"
}

###
DELETE http://localhost:8081/accounts/5b79e997-b67e-4ac4-a337-ab3b485f9736 HTTP/1.1


### 
POST http://localhost:8081/cash HTTP/1.1
Content-Type: application/json

{
  "accountId": "af8ca419-9b44-4186-9f97-d4fa523b6d5c",
  "amountChange": 20000,
  "opType": "CASHING_OUT"
}

### 
POST http://localhost:8081/transfer/by_account_id HTTP/1.1
Content-Type: application/json

{
  "senderAccountId": "12c4aaac-735b-4263-a381-7c788648870c",
  "recipientAccountId": "af8ca419-9b44-4186-9f97-d4fa523b6d5c",
  "transferAmount": 6000
}