version: "3"

volumes:
  postgres_data: {}
  postgres_data_2: {}
  pgadmin_data: {}

networks:
  app:
    driver: bridge

services:
  postgres:
    container_name: scala-postgres-service1
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    networks:
      - app

  postgres2:
    container_name: scala-postgres-service2
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    networks:
      - app

  pgadmin:
    container_name: scala-pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - app

  scala-money-service1:
    container_name: scala-money-service1
    image: scala-money-service1
    env_file: .env
    ports:
      - "8001:8081"
    build:
      context: ./
      dockerfile: Dockerfile.service1
    networks:
      - app

  scala-money-service2:
    container_name: scala-money-service2
    image: scala-money-service2
    env_file: .env
    ports:
      - "8002:8081"
    build:
      context: ./
      dockerfile: Dockerfile.service2
    networks:
      - app
